import { useMemo, useState } from 'react';
import { BOOKING_STATUS } from '../types/models';
import { formatTimeRange } from '../utils/helpers';
const dateKey = date => `${date.getFullYear()}-${String(date.getMonth() + 1).padStart(2, '0')}-${String(date.getDate()).padStart(2, '0')}`;
const monthTitle = month => new Intl.DateTimeFormat('en-US', { month: 'long', year: 'numeric' }).format(month);
function groupSessions(bookings, currentUid) { const sessions = new Map(); bookings.forEach(booking => { const key = booking.skillId ? `${booking.skillId}-${booking.availableDate || ''}-${booking.startTime || ''}` : booking.id; const existing = sessions.get(key); const participants = new Set([...(existing?.participantNames || []), ...(booking.participantNames || []), booking.buyerName].filter(Boolean)); if (existing) { existing.participantNames = [...participants]; return; } sessions.set(key, { ...booking, participantNames: [...participants], kind: booking.sellerId === currentUid ? 'teaching' : 'learning' }); }); return [...sessions.values()]; }
function SessionList({ title, icon, sessions, onOpenBooking, kind }) { return <div className={`calendar-session-list ${kind}`}><h3>{icon} {title}</h3>{sessions.length ? sessions.map(session => <button className="calendar-booking" key={session.id} onClick={() => onOpenBooking?.(session.id)}><div><strong>{session.skillTitle}</strong><span>{session.kind === 'teaching' ? `受講者：${session.participantNames.join('、')}` : `先生：${session.sellerName}`}</span></div><small>{session.availableDate} · {formatTimeRange(session.startTime, session.duration)}</small></button>) : <p>この月の予定はありません。</p>}</div>; }
export default function MyCalendar({ bookings, currentUid, onOpenBooking }) {
  const [month, setMonth] = useState(() => new Date(new Date().getFullYear(), new Date().getMonth(), 1)); const [selectedDate, setSelectedDate] = useState(dateKey(new Date()));
  const sessions = useMemo(() => groupSessions(bookings, currentUid), [bookings, currentUid]); const byDay = useMemo(() => sessions.reduce((result, session) => { if (session.availableDate) (result[session.availableDate] ||= []).push(session); return result; }, {}), [sessions]);
  const monthPrefix = `${month.getFullYear()}-${String(month.getMonth() + 1).padStart(2, '0')}`; const upcoming = sessions.filter(session => session.availableDate?.startsWith(monthPrefix) && session.status !== BOOKING_STATUS.COMPLETED).sort((a, b) => `${a.availableDate}${a.startTime}`.localeCompare(`${b.availableDate}${b.startTime}`)); const learning = upcoming.filter(session => session.kind === 'learning'); const teaching = upcoming.filter(session => session.kind === 'teaching');
  const first = new Date(month.getFullYear(), month.getMonth(), 1), dayCount = new Date(month.getFullYear(), month.getMonth() + 1, 0).getDate(), offset = first.getDay(); const cells = Array.from({ length: offset + dayCount }, (_, index) => index < offset ? null : new Date(month.getFullYear(), month.getMonth(), index - offset + 1)); const today = dateKey(new Date());
  return <section className="calendar-section"><div className="calendar-heading"><div><p className="eyebrow">MY CALENDAR</p><h2>My Calendar</h2></div><div className="calendar-controls"><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() - 1, 1))} aria-label="前月">‹</button><strong>{monthTitle(month)}</strong><button onClick={() => setMonth(new Date(month.getFullYear(), month.getMonth() + 1, 1))} aria-label="翌月">›</button></div></div><div className="calendar-grid"><div className="weekdays">{['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'].map(day => <span key={day}>{day}</span>)}</div><div className="days">{cells.map((date, index) => { const key = date && dateKey(date), items = key ? byDay[key] || [] : []; return date ? <button key={key} className={`day ${key === today ? 'today' : ''} ${key === selectedDate ? 'selected' : ''}`} onClick={() => setSelectedDate(key)}><span>{date.getDate()}</span><div className="calendar-events">{items.slice(0, 2).map(item => <em className={item.kind} key={item.id}>{item.category || item.subject}<small>{item.startTime}</small></em>)}{items.length > 2 && <em>+{items.length - 2}件</em>}</div></button> : <span key={`blank-${index}`} />; })}</div></div><div className="calendar-details"><b>{monthTitle(month)} の予約一覧</b><div className="calendar-session-columns"><SessionList title="受講予定" icon="📘" sessions={learning} onOpenBooking={onOpenBooking} kind="learning" /><SessionList title="教える予定" icon="📚" sessions={teaching} onOpenBooking={onOpenBooking} kind="teaching" /></div></div></section>;
}
